# BEFORE RUN:
# gradlew clean
# gradlew bootJar
#
# RUN:
# docker-compose build
# docker-compose up

version: '3'

services:
  config-service:
    build: config-service/
    restart: always
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
#    ports: #remove ports in production
#      - 8081:8081

  registry-service:
    build: registry-service/
    restart: always
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    depends_on:
      - config-service
#    ports: #remove ports in production
#      - 8761:8761

  auth-service:
    build: auth-service/
    restart: always
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      USER_SERVICE_PASSWORD: ${USER_SERVICE_PASSWORD}
      DEBTS_SERVICE_PASSWORD: ${DEBTS_SERVICE_PASSWORD}
      AUTH_SERVICE_DB_USERNAME: ${AUTH_SERVICE_DB_USERNAME}
      AUTH_SERVICE_DB_PASSWORD: ${AUTH_SERVICE_DB_PASSWORD}
      AUTH_SERVICE_DB_NAME: ${AUTH_SERVICE_DB_NAME}
    depends_on:
      - config-service
      - registry-service
      - database
#    ports: #remove ports in production
#      - 8084:8084

  user-service:
    build: user-service/
    restart: always
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      USER_SERVICE_PASSWORD: ${USER_SERVICE_PASSWORD}
      USER_SERVICE_DB_USERNAME: ${USER_SERVICE_DB_USERNAME}
      USER_SERVICE_DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      USER_SERVICE_DB_NAME: ${USER_SERVICE_DB_NAME}
    depends_on:
      - config-service
      - registry-service
      - database
#    ports: #remove ports in production
#      - 8085:8085

  debts-service:
    build: debts-service/
    restart: always
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      DEBTS_SERVICE_PASSWORD: ${DEBTS_SERVICE_PASSWORD}
      DEBTS_SERVICE_DB_USERNAME: ${DEBTS_SERVICE_DB_USERNAME}
      DEBTS_SERVICE_DB_PASSWORD: ${DEBTS_SERVICE_DB_PASSWORD}
      DEBTS_SERVICE_DB_NAME: ${DEBTS_SERVICE_DB_NAME}
    depends_on:
      - config-service
      - registry-service
      - database
#    ports: #remove ports in production
#      - 8086:8086

  gateway:
    build: gateway/
    restart: always
    environment:
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    depends_on:
      - config-service
      - registry-service
    ports:
    - 4000:4000

 #TODO: FIX
  database:
    build: database/
    restart: always
#    volumes:
#      - ./db/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_NAME}
#    ports: #remove ports in production
#      - 5432:5432
