server:
  port: 8084

service-secrets:
  user-service: ${USER_SERVICE_PASSWORD}
  debts-service: ${DEBTS_SERVICE_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

spring:
  application:
    name: auth-service
  h2: # http://localhost:8084/h2-console/
    console:
      enabled: true # TODO: fix access

  datasource:
    url: jdbc:postgresql://database:5432/${AUTH_SERVICE_DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${AUTH_SERVICE_DB_USERNAME}
    password: ${AUTH_SERVICE_DB_PASSWORD}

  jpa:
    show-sql: false
    database-platform: postgres
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
