server:
  port: 8084

service-secrets:
  user-service: USER_SERVICE_PASSWORD
  debts-service: DEBTS_SERVICE_PASSWORD

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

spring:
  application:
    name: auth-service
  h2: # http://localhost:8084/h2-console/
    console:
      enabled: true # TODO: fix access
  datasource:
    url: jdbc:postgresql://database:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pswd
  jpa:
    show-sql: false
    database-platform: postgres
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
