#TODO: Secure actuator

server:
  port: 4000

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

zuul:
  routes:
    auth-service:
      path: /auth/**
      url: http://auth-service:8084/auth
      stripPrefix: true
      sensitiveHeaders:

    auth-service-token:
      path: /oauth/**
      url: http://auth-service:8084/oauth
      stripPrefix: true
      sensitiveHeaders:

    user-service-user:
      path: /user/**
      url: http://user-service:8085/user
      stripPrefix: true
      sensitiveHeaders:

    user-service-friends:
      path: /friends/**
      url: http://user-service:8085/friends
      stripPrefix: true
      sensitiveHeaders:

    debts-service:
      path: /debts/**
      url: http://debts-service:8086/debts
      stripPrefix: true
      sensitiveHeaders:
