#TODO: Fix actuator access

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      clientId: user-service
      clientSecret: USER_SERVICE_PASSWORD
      accessTokenUri: http://localhost:8084/oauth/token
      tokenInfoUri: http://localhost:8084/oauth/check_token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:8084/current

spring:
  application:
    name: user-service
  h2: # http://localhost:8085/h2-console/
    console:
      enabled: true # TODO: fix access

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pswd

  jpa:
    show-sql: false
    database-platform: postgres
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
