server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

security:
  oauth2:
    client:
      clientId: user-service
      clientSecret: ${USER_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:8084/oauth/token
      tokenInfoUri: http://auth-service:8084/oauth/check_token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://auth-service:8084/auth/current

spring:
  application:
    name: user-service
  h2: # http://localhost:8085/h2-console/
    console:
      enabled: true # TODO: fix access

  datasource:
    url: jdbc:postgresql://database:5432/${USER_SERVICE_DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}

  jpa:
    show-sql: false
    database-platform: postgres
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
