#TODO: fix actuator access

server:
  port: 8081

#TODO: add configuration refresh
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  security:
    user:
      #TODO: use 2 profiles (dev and docker) or do something with env for dev
      password: ${CONFIG_SERVICE_PASSWORD}

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    ru.drsanches.config_service: INFO