server:
  port: 8081

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    ru.drsanches.config_service: INFO